# -*- coding: utf-8 -*-
"""음식 분석 스크립트

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bgOxKRuNAprhnL0U9Dnv1U3BfoXnfKUd
"""

# -*- coding: utf-8 -*-
"""
음식물 쓰레기 이미지 분석 및 리포트 생성 스크립트
"""
from dotenv import load_dotenv
load_dotenv()

import base64
import os
import json
from openai import OpenAI
from langchain_openai import ChatOpenAI
from langchain.prompts import PromptTemplate
from langgraph.graph import StateGraph, END
from typing import TypedDict

# -----------------------------
# 0. 초기화
# -----------------------------
# API 키는 환경 변수(OPENAI_API_KEY)에 설정해두는 것이 좋습니다.
try:
    client = OpenAI()
    llm = ChatOpenAI(model="gpt-4o", temperature=0)
except Exception as e:
    print(f"🚨 OpenAI 또는 LangChain 초기화 중 오류가 발생했습니다.")
    print("OPENAI_API_KEY가 올바르게 설정되었는지 확인해주세요.")
    print(f"오류 상세: {e}")
    exit()


# -----------------------------
# 상태 정의
# -----------------------------
class State(TypedDict):
    analysis: str
    report: str
    improvements: str


# -----------------------------
# 1. 멀티모달 분석 함수
# -----------------------------
def analyze_food(image_path: str) -> str:
    """이미지 경로를 받아 GPT-4o로 분석하고 결과를 JSON 문자열로 반환합니다."""
    try:
        with open(image_path, "rb") as f:
            img_bytes = f.read()
        img_base64 = base64.b64encode(img_bytes).decode("utf-8")

        response = client.chat.completions.create(
            model="gpt-4o",
            messages=[
                {
                    "role": "system",
                    "content": "당신은 남긴 음식 분석 전문가입니다. JSON 형식으로만 답변하세요.",
                },
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "text",
                            "text": "이 음식 사진을 보고 음식 종류와 남은 양을 JSON 형식으로 분석해주세요.",
                        },
                        {
                            "type": "image_url",
                            "image_url": {
                                "url": f"data:image/jpeg;base64,{img_base64}"
                            },
                        },
                    ],
                },
            ],
        )
        return response.choices[0].message.content
    except FileNotFoundError:
        print(f"오류: 이미지 파일을 찾을 수 없습니다. 경로를 확인하세요: {image_path}")
        return None
    except Exception as e:
        print(f"분석 중 오류 발생: {e}")
        return None


# -----------------------------
# 2. 단일 노드: report + improve 통합
# -----------------------------
combined_prompt = PromptTemplate(
    input_variables=["analysis"],
    template="""
분석 결과: {analysis}

1) 순수 텍스트 잔반 리포트를 작성하세요.
2) 반드시 개선 방안을 1~3개 JSON 배열 형식으로 작성하세요.
3) 절대 improvements를 비워두지 마세요.
4) 출력은 **순수 JSON만** 반환하세요. Markdown, 리스트, 글머리표 등은 절대 포함하지 마세요.

출력 예시(JSON 형식):
{{
  "report": "오늘 제공된 음식의 잔반이 ...",
  "improvements": [
    {{"suggestion": "샐러드 양 조절"}},
    {{"suggestion": "드레싱 종류 다양화"}}
  ]
}}
""",
)
# LangChain Expression Language (LCEL)을 사용하여 체인 구성
combined_chain = combined_prompt | llm


def combined_node(state: State):
    result = combined_chain.invoke({"analysis": state["analysis"]})
    try:
        # 문자열 JSON → dict로 변환
        output = json.loads(result.content)
    except json.JSONDecodeError:
        # 파싱 실패 시 최소한 report만 반환
        output = {"report": result.content, "improvements": "LLM 출력 파싱 실패"}
    return output


# -----------------------------
# 3. LangGraph 구성
# -----------------------------
def build_graph():
    """LangGraph 워크플로우를 구성하고 컴파일합니다."""
    graph = StateGraph(State)

    graph.add_node("analyze", lambda s: {"analysis": s["analysis"]})
    graph.add_node("combined", combined_node)

    graph.set_entry_point("analyze")
    graph.add_edge("analyze", "combined")
    graph.add_edge("combined", END)

    return graph.compile()


# -----------------------------
# 4. 메인 실행 함수
# -----------------------------
def main():
    """메인 실행 로직"""
    print("--- 음식물 쓰레기 분석기 ---")

    # 실행 예시
    image_path = input(
        "분석할 이미지 파일의 경로를 입력하세요 (예: ./data/Waffles50.jpg): "
    )

    if not os.path.exists(image_path):
        print(f"오류: '{image_path}' 경로에 파일이 없습니다.")
        return

    print("\n1. 이미지를 분석 중입니다...")
    analysis_result = analyze_food(image_path)

    if analysis_result:
        print("분석 완료!")

        app = build_graph()

        print("\n2. 리포트 및 개선 방안을 생성 중입니다...")
        final_output = app.invoke({"analysis": analysis_result})
        print("생성 완료!")

        print("\n--- 최종 결과 ---")
        print("📌 리포트:")
        print(final_output.get("report", "리포트 생성 실패"))

        print("\n📌 개선 방안:")
        improvements = final_output.get("improvements", [])
        if isinstance(improvements, list):
            for item in improvements:
                print(f"- {item.get('suggestion', '개선 방안 없음')}")
        else:
            print(improvements)


if __name__ == "__main__":
    main()
